### ISSUE TITLE
fix link in README.md

### ISSUE THREAD

**Issue by VSerj** [bringmetheaugust/Memory-Storm-2#12]
Actual URL: https://bringmetheaugust.github.io/memoryStorm/
![image](https://user-images.githubusercontent.com/44513805/95655414-ca37c680-0b0f-11eb-9037-75d4338da065.png)

**Comment by bringmetheaugust** [comment]
дело дрянь

**Comment by VSerj** [comment]
добавил PR
Все будет ок

**Comment by bringmetheaugust** [comment]
good job, colleague)

**Comment by VSerj** [comment]
Thanks!

We are a super team!
